name: Migrate One or More Environment Secrets

on:
  push:
  workflow_call:
    inputs:
      json-migration-spec:
        type: string
        required: true
        description: >-
          A JSON structured specification of repositories to be migrated.
  workflow_dispatch:
    inputs:
      json-migration-spec:
        type: string
        required: true
        description: >-
          A JSON structure specification of repositories to be migrated. Th
      # expected json-migration-spec input should be structured as follows:
      # {
      #     "ENVIRONMENT_SECRET_01": {
      #         "secretname": "ENVIRONMENT_SECRET_01",
      #         "destinationEnvironmentName": "production",
      #         "destinationRepositoryId": "706095692",
      #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
      #     },
      #     "ENVIRONMENT_SECRET_02": {
      #         "secretname": "ENVIRONMENT_SECRET_02",
      #         "destinationEnvironmentName": "production",
      #         "destinationRepositoryId": "706096064",
      #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
      #     },
      #     "ENVIRONMENT_SECRET_03": {
      #         "secretname": "ENVIRONMENT_SECRET_03",
      #         "destinationEnvironmentName": "staging",
      #         "destinationRepositoryId": "706096293",
      #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
      #     }
      # }

jobs:
  migrate-environment-secret:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secretname: ${{ fromJSON(inputs.json-migration-spec).*.secretname }} # e.g. [ "x", "y", ...]
      max-parallel: 1
    steps:
      - name: Save environment secret
        uses: github-gk-aks/github-secret-new/save-to-environment@main
        with:
          secret-name: ${{ matrix.secretname }} # e.g. "x"
          secret-value: ${{ secrets[matrix.secretname] }}
          destination-environment: ${{ fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationEnvironmentName }} # e.g. "env-01"
          destination-repository-id: ${{ fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationRepositoryId }} # e.g. "targetRepoIdA"
          destination-github-token: ${{ secrets[fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationPersonalAccessTokenName] }} # e.g. secret["the_pat_a"]