name: Add Teams to GitHub Advanced Security Alerts

on:
  push:

jobs:
  add-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add teams to GitHub Advanced Security
      run: |
        # Set your repository owner and name
        REPO_OWNER=your-repo-owner
        REPO_NAME=your-repo-name

        # Set your GitHub token
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

        # Get repository teams
        teams=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/teams" | jq -r '.[].slug')

        # Loop through teams and add teams to GitHub Advanced Security access list
        for team in $teams; do
          if [ -n "$team" ]; then
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/code-scanning/sarifs/access-control/teams/$team"
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
