name: Add License File

on:
  push:
  workflow_dispatch:
    inputs:
      licenseContent:
        type: string
        description: 'Base64-encoded license content'
        required: true

jobs:
  add-license:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

    #   - name: Decode license content
    #     id: decode-license
    #     run: |
    #       echo "${{ inputs.licenseContent }}" | base64 -d
    #       echo "::set-output name=decoded_license::$(echo "${{ inputs.licenseContent }}" | base64 -d)"

      - name: Check if license file exists
        id: check-license
        run: |
          if [ ! -f "LICENSE" ]; then
            echo "License file not found. Creating..."
            echo "${{ inputs.licenseContent }}" > LICENSE
            git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
            git add LICENSE
            git commit -m "Add LICENSE file"
            git push origin github-migration
          else
            echo "License file found. Skipping..."
          fi
