name: Call Repository Secret Migration Workflow

on:
  push:
  workflow_dispatch:
    inputs:
        repository:
          type: string
          description: 'Repository name'
          required: true

jobs:
  call-rep-secret:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Call Repository Scoped Secret Migration Workflow
        run: |
          gh workflow run secret-migration-repository --ref github-migration -F json-migration-spec=@'${{ github.event.inputs.repository }}'-spec.json