name: Commit Signing Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-commit-signing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@V2

      - name: Import GPG key
        run: echo $GPG_KEY | base64 --decode | gpg --batch --import
        env:
            GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Add the custom gpg siging program that passes the passphrase to the gpg CLI
        run: |
            rm -rf /tmp/gpg.sh
            echo '#!/bin/bash' >> /tmp/gpg.sh
            echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
            chmod +x /tmp/gpg.sh

      - name: Setup git
        run: |
            git config commit.gpgsign true
            git config user.signingkey $GPG_KEY_ID
            git config gpg.program /tmp/gpg.sh
            env:
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Test Commit Sign
        run: |
            echo 'Testing Commit Sign' >> test.md
            git add test.md
            git commit -m "Testing Commit Signing"
            git verify-commit $( git rev-parse HEAD )
        env:
            GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
            GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
            GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
            GIT_AUTHOR_NAME: SomeBot
            GIT_AUTHOR_EMAIL: somebot@example.com

