name: Get environment secret value

on:
  push:
    branches:
        - github-migration
    tags-ignore:
        - '*'

jobs:
  get-env-secret-value:
    name: Get Environment Secret Value
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: preprod
    steps:
        - name: Get environment secret
          run: |
            echo 'Secret name is : ${{ secrets.AWS_DEPLOYMENT_KEY_ID }}' >> env_secret_file.txt

        - name: Upload report
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: env_secret_file.txt
            path: env_secret_file.txt

        